### ISSUE TITLE
Permissions hard reset option/code

### ISSUE THREAD

**Issue by hemipatu** [macdja38/pvpcraft#15]
In the event that someone sets up permissions incorrectly there, on occasion is a problem where we cannot identify to what --channel, --user or --role it has been set to and from what we can tell there is no way to manually remove this permission. For example;

`{
    "191618020571873280": {
        "g190905185739079680": {
            "warframe": {
                "deal": true
            }`

To fix this is it possible to add the option to completely reset all permissions via a command like: //perms set removeall restoring it to the original file which had nothing at all when //perms list is ran.

Thank you :+1:

**Comment by macdja38** [comment]
Added in 5658700 will be deployed within 24h. at the moment the command is //perms hardreset and can only be used by the servers owner.
