### ISSUE TITLE
How to block Music Bot in specify vocal channel

### ISSUE THREAD

**Issue by qlaffont** [macdja38/pvpcraft#24]
I want to restrict vocal channel for init commands (To have music bot), 
how i can do it ?
Regards 
Quentin

**Comment by macdja38** [comment]
At the moment the easiest way is to deny the bot permission to join the voice channel... I could add a node for it and give it to users as default I suppose... in theory it is possible to target a voice channel with permissions so it could work.

**Comment by qlaffont** [comment]
okay, thanks. Nice Work ! If you need some help ask it ! ;)

**Comment by macdja38** [comment]
Ok, I have a prototype working, not sure if I'm going to go with this, and I'll give everyone the permission by default but... looks like it should work.

**Comment by qlaffont** [comment]
Personally I create my bot with a web panel. I can say which person can modify this permission and i just do a "joinVoiceChannel".

**Comment by qlaffont** [comment]
If you want i can give you the code to join a channel !

**Comment by qlaffont** [comment]
I create a feature that you can implement : Poke all specify roles when someone is on one specified channel. This feature can help some community. I create a channel Need Help and all my staff is poked to help this person

**Comment by macdja38** [comment]
Umm... sure I guess, right now what I have it doing is checking for the permission music.initinto in the specific voice channel.

**Comment by qlaffont** [comment]
yes. But I think is better for you and for user to have a web panel (it just my point of view). Because you can assign permission for roles or for one person.

**Comment by macdja38** [comment]
You... can do that with the permissions system...

**Comment by macdja38** [comment]
Ok, @qlaffont it's been committed, not going to bring it live till I finish the documentation on it though.

**Comment by qlaffont** [comment]
No problem i create my bot to do this so i don't use you bot anymore x). Thanks #Discordjs
