### ISSUE TITLE
Music Bug

### ISSUE THREAD

**Issue by qlaffont** [macdja38/pvpcraft#25]
Hi,
I found a bug.
Sometime we have a bug, we are obligated to destroy bot.

`
maxou - Today at 3:45 PM
!!play https://www.youtube.com/watch?v=v2AC41dglnM
Bot MusicBOT - Today at 3:45 PM
Error: Status code 303
Playing GTPlanet -  Brakes (less than sign) E-Brake upload by GTE4everyone - Enzo (905 views) [6 Minutes and 1 Second]
Enqueued GTPlanet -  Brakes (less than sign) E-Brake upload by GTE4everyone - Enzo (905 views) [6 Minutes and 1 Second] currently 0
`

Best Regards 
Quentin

**Comment by macdja38** [comment]
Interesting... it got a 303... How often does this occur, and what video was it playing when it occurred, link if possible.

**Comment by qlaffont** [comment]
!!play https://www.youtube.com/watch?v=v2AC41dglnM

**Comment by qlaffont** [comment]
2 or 3

**Comment by macdja38** [comment]
The video pictured is not the one it's saying it has problems with.

**Comment by qlaffont** [comment]
Okay. So how we can sole this ? x) (I don't know why but when we have a bug we heard a sound from Grand turismo, I don't know if it's you x))

**Comment by qlaffont** [comment]
This sound : https://www.youtube.com/watch?v=37ZT8NoUDbU

**Comment by macdja38** [comment]
Any chance you have the link for `Playing GTPlanet - Brakes (less than sign) E-Brake`

**Comment by qlaffont** [comment]
okay strange because for us it's AC/DC - Thunderstruck

**Comment by macdja38** [comment]
If you look in the error it seems that it's not that video that's the problem.

**Comment by qlaffont** [comment]
Okay. YT Bug
