### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by BurningPixels** [macdja38/pvpcraft#27]
When i start the main.js with node main.js i get the error: SyntaxError: Unexpected token ...
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:374:25)
at Object.Module._extensions..js (module.js:417:10
at Module.load (module.js:344:32)
at Function.Module._load (module.js:301:12)
at Function.Module.runMain (module.js:442:10)
at startup (node.js:136:18)
at node.js:966:3

Can someone please help me?

**Comment by macdja38** [comment]
did you run `npm install` first and did it execute successfully and without errors?

**Comment by BurningPixels** [comment]
yeah and there is one more error: pathtothefile/main.js:79
    args.push( .  .  . progress.argv.slice(2));
                    ^^^

**Comment by macdja38** [comment]
any chance you can paste all the errors in order and everything?

**Comment by BurningPixels** [comment]
here https://gfycat.com/DependableFalseEstuarinecrocodile

**Comment by macdja38** [comment]
lol run it with a recent version of node. anything 6.0+ should probably work.

**Comment by BurningPixels** [comment]
yeah i has v 4.whatever installed... but there is one more problem. The Client crashed all the time (more than 3 times) https://gfycat.com/CalculatingInstructiveBug

**Comment by BurningPixels** [comment]
do you have a solution for that?

**Comment by macdja38** [comment]
could be the auto restart thing one sec.

**Comment by macdja38** [comment]
How many discord's is the bot account it's logging into on?

**Comment by BurningPixels** [comment]
What?

**Comment by BurningPixels** [comment]
What do you mean with "How many discord's is the bot account"?

**Comment by macdja38** [comment]
how many discord servers is it on?

**Comment by BurningPixels** [comment]
Actually on no server.

**Comment by macdja38** [comment]
@BurningPixels did you try setting minDiscords to -1 in the config file?

**Comment by BurningPixels** [comment]
nope I haven't changed the config file.

**Comment by macdja38** [comment]
@BurningPixels ok.. can you?

**Comment by BurningPixels** [comment]
Yeah its worked :D thanks i just get an error that node cant find the module Languages.json

**Comment by macdja38** [comment]
@BurningPixels do you need warframe stuff?

**Comment by BurningPixels** [comment]
nope

**Comment by macdja38** [comment]
ok, it's probably going to be your best bet to disable the warframe module in the config file. just delete the line that refers to it. Alternatively follow the setup and get the files.

**Comment by BurningPixels** [comment]
ok thanks for everything ^^

**Comment by macdja38** [comment]
No problem! you may also want to delete the lines in the config file about the website too so it does not post links to them.

**Comment by BurningPixels** [comment]
just one thing, what means url and musicUrl in the permissionfile?

**Comment by macdja38** [comment]
that's the link it pasts when you run the /list command for music. For pvpcraft it's configured to link to that discord's online music list. URL is I think the same thing but for permissions.

**Comment by BurningPixels** [comment]
ok thanks :D

**Comment by BurningPixels** [comment]
Hey... it's me again... When i try to play music, i get that.

queueCount false
Unhandled Rejection at: Promise Promise {
  _bitField: 18087936,
  _fulfillmentHandler0: 
   { ReqlRuntimeError
       at Connection._processResponse (/home/k/Desktop/pvpcraft-master/node_modules/rethinkdbdash/lib/connection.js:395:15)
       at Socket.<anonymous> (/home/k/Desktop/pvpcraft-master/node_modules/rethinkdbdash/lib/connection.js:201:14)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at Socket.Readable.push (_stream_readable.js:134:10)
       at TCP.onread (net.js:551:20)
     msg: 'Table `test.queue` does not exist.',
     message: 'Table `test.queue` does not exist in:\nr.table("queue").insert({\n^^^^^^^^^^^^^^^^         \n    id: "186103678271356939",\n    server: "SOPAR 4.0  | NO GoT SPOILERS!",\n    text: "general",\n    text_id: "186103678271356939",\n    voice: "General",\n    voice_id: "186103678271356940",\n    queue: [{\n        vid: "https://r3---sn-4g5edn7s.googlevideo.com/videoplayback?itag=22&key=yt6&upn=DBXyiZ00dGk&ratebypass=yes&ipbits=0&nh=IgpwcjAyLmZyYTE2KgkxMjcuMC4wLjE&initcwndbps=1053750&signature=54B7086EF168F0C667FBCCB4AFB9AD953EE48A83.993045E336815B5C62FE77661DC455083F6CFBE3&dur=275.713&ei=aeY9WJ2KC8nDigaKvqLQCA&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&lmt=1477200474889362&mt=1480451343&mv=m&id=o-AOej9o5skRD8B4VO1HvDnmKjygNQAAx9lbF-EUypjmLh&ms=au&expire=1480473289&mime=video%2Fmp4&ip=84.19.166.55&requiressl=yes&mm=31&source=youtube&pl=21&mn=sn-4g5edn7s",\n        title: "Cara buat kek #10 Kek Angry Birds",\n        author: "TTH Channel",\n        length: 0,\n        lengthSeconds: 276,\n        user: {\n            name: "BurningPixels | sad",\n            id: "156864377755140096"\n        }\n    }]\n}, {\n   ^\n    conflict: "replace"\n    ^^^^^^^^^^^^^^^^^^^\n})\n^ \n',
     frames: [ 0 ],
     name: 'ReqlOpFailedError' },
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined } reason: { ReqlRuntimeError
    at Connection._processResponse (/home/k/Desktop/pvpcraft-master/node_modules/rethinkdbdash/lib/connection.js:395:15)
    at Socket.<anonymous> (/home/k/Desktop/pvpcraft-master/node_modules/rethinkdbdash/lib/connection.js:201:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
  msg: 'Table `test.queue` does not exist.',
  message: 'Table `test.queue` does not exist in:\nr.table("queue").insert({\n^^^^^^^^^^^^^^^^         \n    id: "186103678271356939",\n    server: "SOPAR 4.0  | NO GoT SPOILERS!",\n    text: "general",\n    text_id: "186103678271356939",\n    voice: "General",\n    voice_id: "186103678271356940",\n    queue: [{\n        vid: "https://r3---sn-4g5edn7s.googlevideo.com/videoplayback?itag=22&key=yt6&upn=DBXyiZ00dGk&ratebypass=yes&ipbits=0&nh=IgpwcjAyLmZyYTE2KgkxMjcuMC4wLjE&initcwndbps=1053750&signature=54B7086EF168F0C667FBCCB4AFB9AD953EE48A83.993045E336815B5C62FE77661DC455083F6CFBE3&dur=275.713&ei=aeY9WJ2KC8nDigaKvqLQCA&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&lmt=1477200474889362&mt=1480451343&mv=m&id=o-AOej9o5skRD8B4VO1HvDnmKjygNQAAx9lbF-EUypjmLh&ms=au&expire=1480473289&mime=video%2Fmp4&ip=84.19.166.55&requiressl=yes&mm=31&source=youtube&pl=21&mn=sn-4g5edn7s",\n        title: "Cara buat kek #10 Kek Angry Birds",\n        author: "TTH Channel",\n        length: 0,\n        lengthSeconds: 276,\n        user: {\n            name: "BurningPixels | sad",\n            id: "156864377755140096"\n        }\n    }]\n}, {\n   ^\n    conflict: "replace"\n    ^^^^^^^^^^^^^^^^^^^\n})\n^ \n',
  frames: [ 0 ],
  name: 'ReqlOpFailedError' }

**Comment by macdja38** [comment]
simply login to the database's webpanel `localhost:8080` or something and create the table manually should just be one button.

**Comment by macdja38** [comment]
@BurningPixels did that work?
