### ISSUE TITLE
Possibility to monitor voice.join/voice.leave/voice.switch for just for a specific voice channel

### ISSUE THREAD

**Issue by ajurycaba** [macdja38/pvpcraft#28]
can I do an "/feeds start moderation​.voice​.join" just for an specific voice chanel?
like /feeds start moderation​.voice​.join --chanel RANDOM_VOICE_CHANEL
i'm asking because when I enable "moderation​.voice​.join", for example, the bot start to monitor the entire server. Even without admin hole for him.
Just for understanding the context we was using this feature just to receive the notification when someone join the VOICE_CHANEL. And it was working perfectly cause we had just one channel.

**Comment by ajurycaba** [comment]
It would be nice too if we could change the text or maybe just choose for something like /feeds start moderation​.voice​.join**2**
Because on the phone it messy (but on PC is just perfect)
![img_0333](https://cloud.githubusercontent.com/assets/20161624/21981172/ee5b5f6e-dbc4-11e6-9e09-c17b8d480c32.PNG)
![captura-de-tela-2017-01-16-08 22 46](https://cloud.githubusercontent.com/assets/20161624/21981207/0e29ff76-dbc5-11e6-8e6d-72ca4fc1eaf8.png)

**Comment by macdja38** [comment]
if the phone notification is the problem perhaps turn off notifications for your phone in that text channel.

**Comment by macdja38** [comment]
Let me know if the voice channel whitelist permission added here fixes your issue. It's available now on the eris test bot which will roll out shortly https://github.com/macdja38/pvpcraft/commit/8d9d1506826b93333c435450f8e7a337fd8f65a5
