### ISSUE TITLE
Feature request! [Custom commands]

### ISSUE THREAD

**Issue by hemiipatu** [macdja38/pvpcraft#30]
Just wondering if it is possible for a future update to include the ability for custom commands.

**For example;-** Users being able to set a command such as _"!!kappa"_ and the bot will show an image that the admin/mods have defined, either via a weblink or uploading said image that corresponds?

**Comment by macdja38** [comment]
it certainly won't be uploading the images but it could possibly use embeds to hide the url… i'll think about adding something like that in the near future

**Comment by macdja38** [comment]
Blocked by this for now https://github.com/macdja38/pvpsite/issues/11

**Comment by hemipatu** [comment]
Awesome @macdja38 thank you once again!

**Comment by macdja38** [comment]
An initial prototype for this now exists, it's not documented and not on the website, but if you care to read through the src you should be able to figure out how to use the limited set of functionality that does exist.
