### ISSUE TITLE
/baro command is returns same incorrect information

### ISSUE THREAD

**Issue by Atmosquake** [macdja38/pvpcraft#58]
Every time I use the /baro command it just returns with 
"Baro appearing at MercuryHUB in 1 Day and 2 Hours"
Even though Baro is literally here right now.

**Comment by macdja38** [comment]
Seems the world state had not successfully updated since thursday, thanks for letting me know. All the code was fine but the database was having trouble resolving warframe's data domain... probably a google DNS issue...
